version: "3"

services:
  src:
    container_name: compact
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/compact/
    networks:
      - all

networks:
  all:
    ipam:
      driver: default
      config:
        - subnet: 10.3.0.0/16